### ISSUE TITLE
display_point_cloud functin error

### ISSUE THREAD

**Issue by Lgz-tud** [niknap/slidaRtools#7]
Hello,Niknap. 
In demo_workfloe_LidarSimulation.R, the display_point_cloud function on lines 170/179/195 is not able to draw a graph.  

#Error in `if (is.na(col.palette)) ...`:
! the condition has length > 1

I made changes to the code built into the function: 

display_point_cloud <- function(xyz.dt, col.palette=NA, col.var="Z", col.lim=NA, size=1){
  xyz.dt <- data.table(xyz.dt)
  if(is.na(col.palette[1])){   # The original code is：is.na(col.palette)
    col.palette <- colorRampPalette(c("darkblue", "blue", "cyan", "green", "yellow", "orange", "red", "darkred"), space = "Lab")(50)
  }
  if(is.na(col.lim[1])){
    col.lim <- c(floor(min(xyz.dt$Z, na.rm=T)), ceiling(max(xyz.dt$Z, na.rm=T)))
  }
  col.index <- round((length(col.palette)-1) * (xyz.dt[, get(col.var)]-col.lim[1]) / (col.lim[2]-col.lim[1]))+1
  rgl::bg3d("black")
  rgl::plot3d(xyz.dt$X, xyz.dt$Y, xyz.dt$Z, col=col.palette[col.index],
              aspect=F, axes=F, box=F, xlab="", ylab="", zlab="", size=size)
}
# 

![image](https://github.com/user-attachments/assets/7b953c4f-7153-4168-b200-b5c7271d1f3d)

Calling the new settings ensures that the graph is drawn. But I'm not sure if there are any other risks with this change.

：）

**Comment by nikoknapp** [comment]
Thank you for the hint. I updated the code according to your suggestion.
